# Generated by Django 4.2.1 on 2023-08-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster', models.URLField()),
                ('genres', models.CharField(max_length=200)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('year_release', models.PositiveIntegerField()),
                ('metacritic_rating', models.PositiveIntegerField()),
                ('runtime', models.PositiveIntegerField()),
            ],
        ),
    ]
